"""Initial migration

Revision ID: 4051f940e9a4
Revises: 831d00dec985
Create Date: 2025-05-07 23:52:30.776514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4051f940e9a4'
down_revision = '831d00dec985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fastest_lap', sa.String(length=80), nullable=True))
        batch_op.drop_column('actual_winner')
        batch_op.drop_column('points')
        batch_op.drop_column('race_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_name', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('points', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('actual_winner', sa.VARCHAR(length=80), nullable=True))
        batch_op.drop_column('fastest_lap')

    # ### end Alembic commands ###
