"""Add read field to ChatMessage

Revision ID: 6fc7231ebac8
Revises: 3dd28e9c8573
Create Date: 2025-05-15 13:51:57.026976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc7231ebac8'
down_revision = '3dd28e9c8573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('read')

    # ### end Alembic commands ###
